### ISSUE TITLE
Behaviour of @x.setter and @x.deleter

### ISSUE THREAD

**Issue by PFython** [PFython/cleverdict#14]
In using a CleverDict instance to hold passwords (in conjunction with `keyring`) I noticed the setter and delete decorators didn't appear to be working:

```
    @property
    def password(self):
        return keyring.get_password(account, self.username)

    @password.setter
    def password(self, value):
        print("Setting!")
        keyring.set_password(account, self.username, value)

    @password.deleter
    def password(self):
        keyring.delete_password(account, username)
```
```
>>> value = "mysecret"
>>> keyring.set_password(CleverSession.choices[self.url], self.username, value)
>>> self.password
'mysecret'

# set
>>> self.password = "newpassword"
>>> self.password
'mysecret'
>>> self['password']
'newpassword'

# delete
>>> del self.password
>>> self.password
'mysecret'
>>> self['password']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Peter\AppData\Roaming\Python\Python39\site-packages\cleverdict\cleverdict.py", line 168, in __getitem__
    name = self.get_key(name)
  File "C:\Users\Peter\AppData\Roaming\Python\Python39\site-packages\cleverdict\cleverdict.py", line 310, in get_key
    raise KeyError(name)
KeyError: 'password'
```

So I'm just wondering if this is something that has to be worked around, a limitation of `CleverDict`, or if there's something even more *Clever* we can do in `CleverDict` itself so that @x.setter and @x.deleter work as expected right out of the box?

**Comment by salabim** [comment]
It is tricky to try and combine properties with __setattr__ and __getattr__ and __getattribute__.
This stackoverflow article describes it quite well:
https://stackoverflow.com/questions/15750522/class-properties-and-setattr

**Comment by PFython** [comment]
Labelled as "wontfix" after Version 1.8.0 simply because the main authors don't currently have the time for non essential enhancements.  If there's a huge uptake in people using CleverDict and asking for this feature that may change, or if you're reading this why not Fork, develop a solution, and contribute a Pull Request yourself?

**Comment by PFython** [comment]
import keyring

account = "PyPI"
class User:
    def __init__(self):
        self.username = "Pfython"
    @property
    def password(self):
        return keyring.get_password(account, self.username)

    @password.setter
    def password(self, value):
        keyring.set_password(account, self.username, value)

    @password.deleter
    def password(self):
        keyring.delete_password(account, username)
