### ISSUE TITLE
[Documents] Comparison to pydantic

### ISSUE THREAD

**Issue by MartinThoma** [PFython/cleverdict#26]
I was just pointed to this project via my blog article [6 Alternatives to Classes in Python](https://betterprogramming.pub/6-alternatives-to-classes-in-python-6ecb7206377). Do you happen to know pydantic? How does cleverdict compare to pydantic?

**Comment by PFython** [comment]
Hi Martin – I’m afraid I haven’t used pydantic in earnest although it looks really impressive.

 

As one of the co-creators of CleverDict I hope the overview <https://github.com/PFython/cleverdict/blob/master/README.md#1.-OVERVIEW>  summarises the functionality quite well and gives some good examples, but in summary I’d say it’s a simpler package that aims to do a few things really well and has two killer features:

 

Good for these jobs:

*	Switching seamlessly between dict[key] notation, object.attribute notatation, and json, covering many tricky edge cases.
*	Convenient import/export of data

 

Killer feature:

*	You use the built-in autosave/autodelete hooks to do things like save to database, trigger notification, export to file etc. whenever values change and/or are deleted.
*	Create and manage aliases for values e.g. shortcuts, local language variants, and mapping API responses (typically JSON) to existing attribute names of your own objects.

 

Please have a look and us know what you think?

 

All the best,

Peter

 

From: Martin Thoma ***@***.***> 
Sent: 15 March 2021 21:31
To: PFython/cleverdict ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [PFython/cleverdict] [Documents] Comparison to pydantic (#26)

 

I was just pointed to this project via my blog article 6 Alternatives to Classes in Python <https://betterprogramming.pub/6-alternatives-to-classes-in-python-6ecb7206377> . Do you happen to know pydantic? How does cleverdict compare to pydantic?

**Comment by MartinThoma** [comment]
Thank you very much! The hooks was a feature I haven't seen from my first glance at the REAMDE (btw: I love the meme-style intro :laughing: )

**Comment by PFython** [comment]
Many thanks for the kind words Martin!

 

All the best with your projects and writing… I look forward to reading more by you soon hopefully!

Peter
