### ISSUE TITLE
Wrong method used in example in README.md

### ISSUE THREAD

**Issue by dpbarrett** [PFython/cleverdict#28]
In Section 8, you have the following:
```
To deactivate .save() or .delete() separately:

>>> x.set_autosave()
>>> x.set_deleve()
```

At first I thought it was a typo that was supposed to be ```.set_delete()```, but I think it might actually be intended as ```.set_autodelete()```.

**Comment by PFython** [comment]
Sorry for taking so long to get to this Denis and thanks for spotting!
